export const ADD_COMMENT = 'ADD_COMMENT';

export const POSTS_LOADING = 'POSTS_LOADING';
export const POSTS_FAILED = 'POSTS_FAILED';
export const ADD_POSTS = 'ADD_POSTS';

export const ADD_NEWPOST = "ADD_NEWPOST";
export const NEWPOST_LOADING ="NEWPOST_LOADING";
export const NEWPOST_FAILED = "NEWPOST_FAILED";
export const NEWPOST_SUC ="NEWPOST_SUC";
export const SWITCH_REDIRECT ="SWITCH_REDIRECT";

export const ADD_COMMENT_SUCC = "ADD_COMMENT_SUCC";
export const LOAD_COMMENTS ="LOAD_COMMENTS";
export const COMMENTS_FAILED = "COMMENTS_FAILED";
export const IS_LOADING = "IS_LOADING";

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const EDIT_POST_GET_DATA_FAIL= 'EDIT_POST_GET_DATA_FAIL';
export const EDIT_POST_GET_DATA_SUCCESS = 'EDIT_POST_GET_DATA_SUCCESS';
export const EDIT_POST_SUCCESS ='EDIT_POST_SUCCESS';
export const EDIT_POST_FAIL ='EDIT_POST_FAIL';
export const UPDATE_EDIT_POST_STATE ='UPDATE_EDIT_POST_STATE';
export const UPDATE_POST_TITLE='UPDATE_POST_TITLE';
export const UPDATE_POST_CONTENT='UPDATE_POST_CONTENT';